[deployment]
[[deployment.rule]]
shards = "primary"
indexers = ["default"]

[store]
[store.primary]
connection = "postgresql://salka1988:let-me-in@postgres:5432/graph-node"
pool_size = 10

[chains]
ingestor = "block_ingestor_node"

[chains.substreams]
shard = "primary"
protocol = "substreams"
provider = [
  { label = "substreams", details = { type = "substreams", url = "http://firehose:10016" } },
]

