version: '3'
services:
  graph-node:
    build:
      dockerfile: ./docker/Dockerfile
      context: ./fuel-graph-node
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres
      postgres_user: "${DB_USER}"
      postgres_pass: "${DB_PASS}"
      postgres_db: "${DB_NAME}"
      ipfs: 'ipfs:5001'
      GRAPH_LOG: info
      GRAPH_NODE_CONFIG: /config/docker-graph-config.toml
    volumes:
      - './docker-graph-config.toml:/config/docker-graph-config.toml'
  ipfs:
    image: 'ipfs/kubo:v0.14.0'
    volumes:
      - './data/ipfs:/data/ipfs'
  postgres:
    image: 'postgres:14'
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"
      PGDATA: /var/lib/postgresql/data
      POSTGRES_INITDB_ARGS: '-E UTF8 --locale=C'
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
#  firehose:
#    build:
#      context: ./firehose
##    ports:
##      - "10015:10015"
#    volumes:
#      - './data/firehose:/data/storage_dir'
#    command: beta-5.fuel.network
