version: '3'
services:
  firehose:
    build:
      context: ./firehose
    ports:
      - '10015:10015' # Firehose API
      - '10016:10016' # Firehose Websocket
      - '10017:10017' # Firehose Websocket (SSL)
    volumes:
      - './data/firehose:/data/storage_dir'
    command: beta-5.fuel.network