[deployment]
[[deployment.rule]]
shards = "primary"
indexers = [ "fuel-node-indexer" ]

[store]
[store.primary]
connection="postgresql://salka1988:let-me-in@postgres:5432/graph-node"
pool_size = 10

[chains]
ingestor = "block_ingestor_node"

[chains.fuelnet]
shard = "primary"
protocol = "fuel"
provider = [
    { label = "fuel", details = { type = "firehose", url = "http://localhost:10015" }},
]