name: gitpod-docker

on:
  push:
    tags:
      - "v*"
    branches:
      - "develop"

jobs:
  docker:
    runs-on: ubuntu-latest
    if: "${{ !startsWith(github.event.head_commit.message, 'GitBook: [#') }}"
    steps:
      - uses: actions/checkout@v2

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/streamingfast/substreams-gitpod
          tag-sha: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.gitpod
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{steps.docker_meta.outputs.tags}}
          labels: ${{steps.docker_meta.outputs.labels}}
