name: Build and Test

on:
  push:
    branches:
      - master
      - develop
      - "release/v*"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    if: "${{ !startsWith(github.event.head_commit.message, 'GitBook: [#') }}"
    strategy:
      matrix:
        go-version: [ 1.21.x ]
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run Tests
        run: ./bin/test.sh

      - name: Build
        run: go build ./...
