[package]
name = "graph-chain-fuel"
version.workspace = true
edition.workspace = true

[build-dependencies]
tonic-build = { workspace = true }
graph-chain-common = { path = "../common" }

[dependencies]
graph = { path = "../../graph" }
prost = { workspace = true }
prost-types = { workspace = true }
serde = "1.0"
anyhow = "1.0"
semver = "1.0.20"
hex = "0.4.3"

graph-runtime-wasm = { path = "../../runtime/wasm" }
graph-runtime-derive = { path = "../../runtime/derive" }

