# A sharded setup that uses two databases
[store]
[store.primary]
connection = "postgresql://graph:graph@127.0.0.1:5432/graph-test"
pool_size = [ { size = 10 } ]
[store.sgd]
connection = "postgresql://graph:graph@127.0.0.1:5432/graph-sgd"
pool_size = [ { size = 10 } ]

[deployment]
[[deployment.rule]]
match = { name = "abi.*|grafted" }
shard="primary"
indexers = [ "default" ]

[[deployment.rule]]
shard = "sgd"
indexers = [ "default" ]

[chains]
ingestor = "default"

# The tests do not talk to ethereum clients; we use valid free client
# endpoints as an example
[chains.fake_network]
shard = "sgd"
provider = [
  { label = "penguin", url="https://main-light.eth.linkpool.io/", features = [] }
]

[chains.fake_network_shared]
shard = "sgd"
provider = [
  { label = "owl", url="https://rinkeby-light.eth.linkpool.io/", features = [] }
]
