apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fuel-subgraph.fullname" . }}
  labels:
    {{- include "fuel-subgraph.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fuel-subgraph.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fuel-subgraph.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fuel-subgraph.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "./app/start.sh" ]
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: firehose-port-1
              containerPort: {{ .Values.firehose.port1 }}
              protocol: TCP
            - name: firehose-port-2
              containerPort: {{ .Values.firehose.port2 }}
              protocol: TCP
            - name: firehose-port-3
              containerPort: {{ .Values.firehose.port3 }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 10
          volumeMounts:
            - name: fuel-subgraph-vol
              mountPath: "/mnt/db"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: fuel-subgraph-vol
          persistentVolumeClaim:
            claimName: {{ include "fuel-subgraph.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
