apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: { { include "fuel-subgraph.fullname" . } }
  labels: { { - include "fuel-subgraph.labels" . | nindent 4 } }
spec:
  accessModes:
    - { { .Values.app.volume.accessmodes } }
  resources:
    requests:
      storage: { { .Values.app.volume.storagerequests } }
  storageClassName: { { .Values.app.volume.storageclass } }
