{{- if .Values.app.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "fuel-subgraph.fullname" . }}
  labels:
    release: {{ .Values.app.serviceMonitor.prometheusRelease }}
spec:
  selector:
    matchLabels:
      {{- include "fuel-subgraph.labels" . | nindent 4 }}
  endpoints:
    - path: /api/metrics
      port: http
{{- end }}
