apiVersion: v1
kind: Service
metadata:
  name: {{ include "fuel-subgraph.fullname" . }}
  labels: {{- include "fuel-subgraph.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: firehose
  selector: {{- include "fuel-subgraph.selectorLabels" . | nindent 4 }}
